# Generated by Django 5.0.6 on 2024-07-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_showing_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster_image',
            field=models.ImageField(default='', upload_to='posters/'),
            preserve_default=False,
        ),
    ]
