# Generated by Django 5.0.6 on 2024-07-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_film_poster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster_image',
            field=models.ImageField(null=True, upload_to='posters/'),
        ),
    ]
