# Generated by Django 5.0.6 on 2024-07-09 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_city_user_post_code_user_street_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='address',
        ),
        migrations.RemoveField(
            model_name='club',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='club',
            name='email',
        ),
        migrations.AddField(
            model_name='club',
            name='club_manager',
            field=models.ForeignKey(default='', limit_choices_to={'user_type': 'club_manager'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
