# Generated by Django 5.0.6 on 2024-07-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_club_address_remove_club_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_request_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_request_status',
            field=models.CharField(choices=[('none', 'None'), ('requested', 'Requested'), ('approved', 'Approved')], default='none', max_length=20),
        ),
    ]
