# Generated by Django 5.0.6 on 2024-07-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_transaction_cancel_requested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='discount_request_status',
        ),
    ]
